- name: Download EC2 Logs
  hosts: all
  gather_facts: false
  vars:
    script_url: https://raw.githubusercontent.com/aws/amazon-ecs-logs-collector/master/ecs-logs-collector.sh
    script_name: "{{ script_url | basename }}"

  tasks:
    - name: Download ECS Log Collector
      become: true
      ansible.builtin.command:
        chdir: "/tmp"
        cmd: "curl -O {{ script_url }}"

    - name: Collecting logs
      become: true
      ansible.builtin.command:
        chdir: "/tmp"
        cmd: "bash /tmp/{{ script_name }}"

    - name: Find last latest log archive
      become: true
      ansible.builtin.shell:
        cmd: "ls /tmp/collect-i* -t -1 | head -n 1"
      register: ls_cmd

    - name: Fetching log archive
      become: true
      ansible.builtin.fetch:
        src: "{{ ls_cmd.stdout }}"
        dest: .
      register: logfile

    - name: Clean up target host
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/tmp/{{ script_name }}"
        - "{{ ls_cmd.stdout }}"
        - "/tmp/collect"

    - name: debug
      debug:
        msg: "Log collection was downloaded to: {{ logfile.dest }}"

    - name: set variables
      set_fact:
        target_dir: "{{ logfile.dest | dirname | dirname | basename}}"
        target_subdir: "{{ logfile.dest | basename | regex_search('-([0-9]+)\\.', '\\1' ) | first }}"

    - name: set extraction directory
      set_fact:
        extraction_dir: "{{ [ target_dir, target_subdir] | path_join }}"

    - name: Create local directory for log files
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ extraction_dir }}"
        state: directory

    - name: Extracting log files
      delegate_to: localhost
      ansible.builtin.shell:
        cmd: "tar xzf {{ logfile.dest }} -C {{ extraction_dir }}"

    - name: Cleanup
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ logfile.dest }}"
        - "{{ [ target_dir, 'tmp'] | path_join}}"

    - name: Finish
      debug:
        msg: "Log collection was extracted to: {{ extraction_dir }}"